Set up Configuration

In [1]:
%load_ext sql

In [2]:
# ID와 PW를 자신의 환경에 맞게 수정
%sql postgresql://wmfrlek99:*******@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev

'Connected: wmfrlek99@dev'

# **이후 아래 SQL에서 "keeyong"을 자신의 스키마로 변경**

다양한 SELECT 실행해보기

In [3]:
%%sql

SELECT *
FROM raw_data.user_session_channel
LIMIT 10;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
10 rows affected.

[(1651, '0004289ee1c7b8b08c77e19878106ae3', 'Organic'),
 (1197, '00053f5e11d1fe4e49a221165b39abc9', 'Facebook'),
 (1401, '00056c20eb5a029583db75506953f1d9', 'Facebook'),
 (1399, '00063cb5da1826febf178b669eea3250', 'Facebook'),
 (1667, '000958fdaefe0dd06f5d7c4e4a5f28d1', 'Instagram'),
 (468, '000a3f777828d2cdbee98887561aa130', 'Facebook'),
 (1563, '000cb7efa8a05429dd5309b4bea2eb0c', 'Naver'),
 (711, '00106ac9184e7d54b570d0f0cb0c38b2', 'Organic'),
 (473, '0011df6282fe8cf78feeab676fbc3c27', 'Naver'),
 (420, '00126b47d5502dfb7d01f750ad23d813', 'Facebook')]

In [4]:
%%sql

SELECT DISTINCT channel                      -- 유일한 채널 이름을 알고 싶은 경우
FROM raw_data.user_session_channel;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
6 rows affected.

[('Organic',),
 ('Google',),
 ('Naver',),
 ('Youtube',),
 ('Instagram',),
 ('Facebook',)]

In [5]:
%%sql

SELECT COUNT(1)                    -- 테이블의 모든 레코드 수 카운트. COUNT(*). 하나의 레코드
FROM raw_data.user_session_channel;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(101520,)]

### 비어 있는 테이블 만들고 레코드 추가하고 COUNT하기

In [6]:
%%sql

DROP TABLE IF EXISTS wmfrlek99.test_table;
CREATE TABLE wmfrlek99.test_table (
    value int
);

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.
Done.

[]

In [7]:
%%sql

INSERT INTO wmfrlek99.test_table VALUES (NULL), (1), (1), (0), (0), (4), (3);

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[]

In [8]:
%%sql

SELECT * FROM wmfrlek99.test_table;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[(None,), (1,), (1,), (0,), (0,), (4,), (3,)]

아래 COUNT 문들의 결과값은 얼마일까?

In [9]:
%%sql

SELECT COUNT(1), COUNT(value), COUNT(DISTINCT value)
FROM wmfrlek99.test_table;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(7, 6, 4)]

### Primary Key 이해해보기와 Data Quality 검사해보기

In [10]:
%%sql

DROP TABLE IF EXISTS wmfrlek99.test_channel;
CREATE TABLE wmfrlek99.test_channel (
   channel varchar(32) primary key,
   description varchar(64) default 'test'
);

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.
Done.

[]

In [11]:
%%sql

INSERT INTO wmfrlek99.test_channel VALUES ('FACEBOOK', 'test'), ('GOOGLE', 'test');

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
2 rows affected.

[]

In [12]:
%%sql

SELECT * FROM wmfrlek99.test_channel;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
2 rows affected.

[('FACEBOOK', 'test'), ('GOOGLE', 'test')]

In [13]:
%%sql

INSERT INTO wmfrlek99.test_channel VALUES ('FACEBOOK'), ('GOOGLE');

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
2 rows affected.

[]

In [14]:
%%sql

-- 데이터웨어하우스 redshift는 primary key가 적용이 안됨


SELECT * FROM wmfrlek99.test_channel;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
4 rows affected.

[('FACEBOOK', 'test'),
 ('GOOGLE', 'test'),
 ('FACEBOOK', 'test'),
 ('GOOGLE', 'test')]

In [15]:
%%sql

SELECT DISTINCT * FROM wmfrlek99.test_channel;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
2 rows affected.

[('FACEBOOK', 'test'), ('GOOGLE', 'test')]

필드 이름 변경해보기

In [16]:

%%sql

ALTER TABLE wmfrlek99.test_channel RENAME channel to channelname;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.

[]

중복 레코드 확인해보기

In [17]:
%%sql

SELECT COUNT(1) FROM wmfrlek99.test_channel;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(4,)]

In [18]:
%%sql

SELECT COUNT(1) FROM (
    SEL
    ECT DISTINCT * FROM wmfrlek99.test_channel
);

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
(psycopg2.errors.SyntaxError) syntax error at or near "DISTINCT"
LINE 3:     ECT DISTINCT * FROM wmfrlek99.test_channel
                ^

[SQL: SELECT COUNT(1) FROM (
    SEL
    ECT DISTINCT * FROM wmfrlek99.test_channel
);]
(Background on this error at: https://sqlalche.me/e/14/f405)

primary key uniqueness 확인해보기

In [19]:
%%sql

SELECT channelname, count(1)
FROM wmfrlek99.test_channel
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[('FACEBOOK', 2)]

타임 스탬프 필드가 있다면 최근에도 업데이트된 레코드가 있는지 꼭 확인. 언제부터 레코드가 생성되었는지도 확인. 월별로 레코드수를 확인해보는 것도 좋은 버릇

In [20]:
%%sql

SELECT MAX(ts), MIN(ts)
FROM raw_data.session_timestamp;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(datetime.datetime(2019, 11, 30, 23, 58, 23), datetime.datetime(2019, 5, 1, 0, 13, 11, 783000))]

### CASE WHEN을 사용해보기

In [21]:
%%sql

SELECT LEFT(ts, 7), COUNT(1)
FROM raw_data.session_timestamp
GROUP BY 1;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[('2019-11', 18059),
 ('2019-08', 17151),
 ('2019-10', 18899),
 ('2019-07', 14840),
 ('2019-09', 15790),
 ('2019-05', 6261),
 ('2019-06', 10520)]

월별로 10000 혹은 그 이상 세션이면 ">= 10,000" 아니면 "< 10,000" 이렇게 찍어보기

In [22]:
%%sql

SELECT LEFT(ts, 7), CASE WHEN COUNT(1) >= 10000 THEN '>= 10,000' ELSE '< 10,000' END
FROM raw_data.session_timestamp
GROUP BY 1;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[('2019-08', '>= 10,000'),
 ('2019-11', '>= 10,000'),
 ('2019-07', '>= 10,000'),
 ('2019-06', '>= 10,000'),
 ('2019-09', '>= 10,000'),
 ('2019-10', '>= 10,000'),
 ('2019-05', '< 10,000')]

월별로 15000 혹은 그 이상 세션이면 ">= 15,000", 10000보다 작으면 "< 10,000", 그 사이이면 "10000 and 15000" 이렇게 찍어보기

In [23]:
%%sql

SELECT
    LEFT(ts, 7),
    CASE 
        WHEN COUNT(1) >= 15000 THEN '>= 15,000'
        WHEN COUNT(1) < 10000 THEN '< 10,000'
        ELSE '10000 and 15000'
    END
FROM raw_data.session_timestamp
GROUP BY 1
ORDER BY 1;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[('2019-05', '< 10,000'),
 ('2019-06', '10000 and 15000'),
 ('2019-07', '10000 and 15000'),
 ('2019-08', '>= 15,000'),
 ('2019-09', '>= 15,000'),
 ('2019-10', '>= 15,000'),
 ('2019-11', '>= 15,000')]

### 공백이 들어있는 필드이름 혹은 예약된 키워드를 필드이름으로 사용하려면?

In [24]:
%%sql

-- field 이름 사이에 공백이 있으면 안됨, field 안에 group을 사용하지 못함.

DROP TABLE IF EXISTS wmfrlek99.test;
CREATE TABLE wmfrlek99.test (
    group int primary key,
    'mailing address' varchar(32)
);

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.
(psycopg2.errors.SyntaxError) syntax error at or near "group"
LINE 2:     group int primary key,
            ^

[SQL: CREATE TABLE wmfrlek99.test (
    group int primary key,
    'mailing address' varchar(32)
);]
(Background on this error at: https://sqlalche.me/e/14/f405)

In [25]:
%%sql

CREATE TABLE wmfrlek99.test (
    "group" int primary key,
    "mail
    ing address" varchar(32)
);

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.

[]

In [26]:
%%sql

SELECT "group"
FROM wmfrlek99.test;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
0 rows affected.

[]

### 다양한 WHERE clause 사용해보기

WHERE에서 "in"을 사용한 clause 사용해보기

In [27]:
%%sql

SELECT COUNT(1)
FROM raw_data.user_session_channel
WHERE channel in ('Google','Facebook');  -- not in

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(33773,)]

In [28]:
%%sql

SELECT COUNT(1)
FROM raw_data.user_session_channel
WHERE channel like '%oo%';   -- not like

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(33773,)]

In [29]:
%%sql

SELECT COUNT(1)
FROM raw_data.user_session_channel
WHERE channel like 'F%';

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(16791,)]

In [30]:
%%sql

SELECT COUNT(1)
FROM raw_data.session_timestamp
WHERE ts BETWEEN '2019-05-01' and '2019-06-01'; -- a와 b다 포함

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(6261,)]

### NULL과 TRUE/FALSE 이해하기

In [31]:
%%sql

SELECT *
FROM wmfrlek99.test_table

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[(None,), (1,), (1,), (0,), (0,), (4,), (3,)]

In [32]:
%%sql

SELECT COUNT(1)
FROM wmfrlek99.test_table
WHERE value is NULL; -- primary key로 지정된 필드에 꼭 해보는 것이 좋음. WHERE value != NULL이 아님. IS NULL의 반대는 IS NOT NULL

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(1,)]

In [33]:
%%sql

-- NULL을 비교할 때는 =, != 를 사용하는것이 아닌 IS나 ISNULL을 사용해야함

SELECT COUNT(1)
FROM wmfrlek99.test_table
WHERE value = NULL;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(0,)]

기본적으로 필드는 NULL 값을 가질 수 있음. 만일 어느 필드의 값이 NULL이 될 수 없다면 CREATE TABLE 실행시 지정가능

In [34]:
%%sql

DROP TABLE IF EXISTS wmfrlek99.test_null;
CREATE TABLE wmfrlek99.test_null (
    value int NOT NULL --속성으로 not null을 지정해줌
);

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.
Done.

[]

In [35]:
%%sql


INSERT INTO wmfrlek99.test_null VALUES (NULL);

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev

InternalError: ignored

Boolean 필터링과 NULL과의 관계

In [36]:
%%sql

DROP TABLE IF EXISTS wmfrlek99.test_boolean;
CREATE TABLE wmfrlek99.test_boolean (
    value boolean 
)

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.
Done.

[]

In [37]:
%%sql

INSERT INTO wmfrlek99.test_boolean VALUES (True), (False), (True), (True), (True), (NULL);

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
6 rows affected.

[]

In [38]:
%%sql

SELECT * FROM wmfrlek99.test_boolean;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
6 rows affected.

[(True,), (False,), (True,), (True,), (True,), (None,)]

In [39]:
%%sql

SELECT COUNT(1) FROM wmfrlek99.test_boolean WHERE value IS False;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(1,)]

In [40]:
%%sql
-- is False나 is not True나 수학적으로 같아 보일 수 있어도 NULL때문에 반환하는 값이 다름. 주의할 것 !
SELECT COUNT(1) FROM wmfrlek99.test_boolean WHERE value is not True;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(2,)]

NULL이 들어간 경우의 연산은?

In [41]:
%%sql

SELECT COUNT(NULL);

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(0,)]

In [42]:
%%sql

SELECT 1/NULL;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(None,)]

In [43]:
%%sql

SELECT 0+NULL;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(None,)]

### COALESCE, NULLIF

In [ ]:
%%sql

SELECT 100/value
FROM wmfrlek99.test_table;
--value에 0이 있기 때문에 에러가 생김

In [45]:
%%sql
-- nullif를 통해 값에 0이 있으면 이를 null로 반환하고 나눔
SELECT value, 100/NULLIF(value, 0)
FROM wmfrlek99.test_table;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[(None, None), (1, 100), (1, 100), (0, None), (0, None), (4, 25), (3, 33)]

In [ ]:
%%sql

SELECT value, COALESCE(value, 1) -- NULL인 경우 1을 대신 사용하고 싶다면
FROM wmfrlek99.test_table;

세션이 가장 많이 생성된 시간대는?

In [46]:
%%sql

SELECT EXTRACT(HOUR FROM ts), COUNT(1) as session_count
FROM raw_data.session_timestamp
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(15, 15339)]

가장 많이 사용된 채널은 무엇인가?

In [47]:
%%sql

SELECT
    channel,
    COUNT(1) AS session_count,
    COUNT(DISTINCT userId) AS user_count
FROM raw_data.user_session_channel
GROUP BY 1                         -- GROUP BY channel
ORDER BY 2 DESC;              -- ORDER BY session_count DESC

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
6 rows affected.

[('Youtube', 17091, 889),
 ('Google', 16982, 893),
 ('Naver', 16921, 882),
 ('Organic', 16904, 895),
 ('Instagram', 16831, 895),
 ('Facebook', 16791, 889)]

가장 많은 세션을 만들어낸 사용자 ID는 무엇인가?

In [48]:
%%sql

SELECT
    userId,
    COUNT(1) AS count
FROM raw_data.user_session_channel
GROUP BY 1                         -- GROUP BY userId
ORDER BY 2 DESC              -- ORDER BY count DESC
LIMIT 1;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(1615, 528)]

월별 채널별 유니크한 사용자 수

In [49]:
%%sql

SELECT 
  TO_CHAR(A.ts, 'YYYY-MM') AS month,
  channel,
  COUNT(DISTINCT B.userid) AS mau
FROM raw_data.session_timestamp A
JOIN raw_data.user_session_channel B ON A.sessionid = B.sessionid
GROUP BY 1, 2      
ORDER BY 1 DESC, 2;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
42 rows affected.

[('2019-11', 'Facebook', 688),
 ('2019-11', 'Google', 688),
 ('2019-11', 'Instagram', 669),
 ('2019-11', 'Naver', 667),
 ('2019-11', 'Organic', 677),
 ('2019-11', 'Youtube', 677),
 ('2019-10', 'Facebook', 698),
 ('2019-10', 'Google', 699),
 ('2019-10', 'Instagram', 707),
 ('2019-10', 'Naver', 713),
 ('2019-10', 'Organic', 709),
 ('2019-10', 'Youtube', 705),
 ('2019-09', 'Facebook', 597),
 ('2019-09', 'Google', 599),
 ('2019-09', 'Instagram', 588),
 ('2019-09', 'Naver', 592),
 ('2019-09', 'Organic', 592),
 ('2019-09', 'Youtube', 588),
 ('2019-08', 'Facebook', 611),
 ('2019-08', 'Google', 610),
 ('2019-08', 'Instagram', 621),
 ('2019-08', 'Naver', 626),
 ('2019-08', 'Organic', 608),
 ('2019-08', 'Youtube', 614),
 ('2019-07', 'Facebook', 558),
 ('2019-07', 'Google', 556),
 ('2019-07', 'Instagram', 567),
 ('2019-07', 'Naver', 553),
 ('2019-07', 'Organic', 557),
 ('2019-07', 'Youtube', 564),
 ('2019-06', 'Facebook', 414),
 ('2019-06', 'Google', 412),
 ('2019-06', 'Instagram', 410),
 ('2019-06', 'Naver', 398),
 ('2019-06', 'Organic', 416),
 ('2019-06', 'Youtube', 400),
 ('2019-05', 'Facebook', 247),
 ('2019-05', 'Google', 253),
 ('2019-05', 'Instagram', 234),
 ('2019-05', 'Naver', 237),
 ('2019-05', 'Organic', 238),
 ('2019-05', 'Youtube', 244)]

### 요약 테이블을 CTAS (Create Table 이름 As SELECT)로 생성해보기

In [50]:
%%sql
--이미 input data에 내가 원하는 정보를 가지고 있을 경우 이를 바탕으로 새로운 테이블을 만들어 내는 경우
CREATE TABLE wmfrlek99.monthly_active_user_summary AS 
SELECT TO_CHAR(ts, 'YYYY-MM') AS month, COUNT(DISTINCT userid)
FROM raw_data.user_session_channel A
JOIN raw_data.session_timestamp B ON A.sessionid = B.sessionid
GROUP BY 1
ORDER BY 1 DESC;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.

[]

In [51]:
%%sql

SELECT * FROM wmfrlek99.monthly_active_user_summary;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[('2019-11', 721),
 ('2019-08', 662),
 ('2019-10', 763),
 ('2019-09', 639),
 ('2019-07', 623),
 ('2019-06', 459),
 ('2019-05', 281)]

In [52]:
%%sql

DROP TABLE wmfrlek99.monthly_active_user_summary;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.

[]

In [53]:
%%sql

SELECT EXTRACT(HOUR FROM ts), COUNT(1)
FROM raw_data.session_timestamp
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(15, 15339)]

In [54]:
%%sql

SELECT EXTRACT(DOW FROM ts), COUNT(1)
FROM raw_data.session_timestamp
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(5, 15091)]

In [55]:
%%sql

SELECT EXTRACT(DOW FROM ts), EXTRACT(HOUR FROM ts), COUNT(1)
FROM raw_data.session_timestamp
GROUP BY 1, 2
ORDER BY 3 DESC
LIMIT 1;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(5, 15, 2290)]

In [56]:
%%sql

SELECT ts, channel
FROM raw_data.user_session_channel usc
JOIN raw_data.session_timestamp st ON usc.sessionid = st.sessionid
WHERE userid = 251
ORDER BY 1;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
216 rows affected.

[(datetime.datetime(2019, 5, 1, 12, 18, 26, 637000), 'Facebook'),
 (datetime.datetime(2019, 5, 2, 13, 6, 12, 47000), 'Instagram'),
 (datetime.datetime(2019, 5, 3, 13, 43, 21, 857000), 'Instagram'),
 (datetime.datetime(2019, 5, 4, 13, 54, 0, 610000), 'Instagram'),
 (datetime.datetime(2019, 5, 5, 13, 30, 8, 260000), 'Google'),
 (datetime.datetime(2019, 5, 6, 12, 36, 54, 80000), 'Youtube'),
 (datetime.datetime(2019, 5, 7, 12, 22, 45, 713000), 'Youtube'),
 (datetime.datetime(2019, 5, 8, 12, 27, 53, 360000), 'Organic'),
 (datetime.datetime(2019, 5, 9, 11, 54, 21, 527000), 'Youtube'),
 (datetime.datetime(2019, 5, 10, 14, 29, 36, 197000), 'Facebook'),
 (datetime.datetime(2019, 5, 11, 12, 42, 13, 727000), 'Facebook'),
 (datetime.datetime(2019, 5, 12, 12, 46, 57, 153000), 'Youtube'),
 (datetime.datetime(2019, 5, 13, 11, 56, 26, 650000), 'Google'),
 (datetime.datetime(2019, 5, 14, 12, 50, 53, 303000), 'Youtube'),
 (datetime.datetime(2019, 5, 15, 12, 39, 16, 610000), 'Organic'),
 (datetime.datetime(2019, 5, 16, 12, 31, 56, 140000), 'Instagram'),
 (datetime.datetime(2019, 5, 17, 13, 6, 3, 367000), 'Youtube'),
 (datetime.datetime(2019, 5, 18, 12, 32, 12, 420000), 'Youtube'),
 (datetime.datetime(2019, 5, 19, 13, 35, 51, 503000), 'Organic'),
 (datetime.datetime(2019, 5, 20, 12, 59, 25, 773000), 'Naver'),
 (datetime.datetime(2019, 5, 21, 12, 17, 36, 223000), 'Instagram'),
 (datetime.datetime(2019, 5, 21, 12, 25, 44, 910000), 'Instagram'),
 (datetime.datetime(2019, 5, 22, 12, 59, 50, 550000), 'Organic'),
 (datetime.datetime(2019, 5, 23, 12, 31, 3, 600000), 'Instagram'),
 (datetime.datetime(2019, 5, 24, 13, 15, 30, 607000), 'Naver'),
 (datetime.datetime(2019, 5, 25, 12, 46, 54, 253000), 'Facebook'),
 (datetime.datetime(2019, 5, 26, 13, 6, 16, 913000), 'Google'),
 (datetime.datetime(2019, 5, 27, 13, 15, 41, 573000), 'Youtube'),
 (datetime.datetime(2019, 5, 28, 11, 53, 17, 513000), 'Organic'),
 (datetime.datetime(2019, 5, 29, 12, 33, 2, 777000), 'Instagram'),
 (datetime.datetime(2019, 5, 30, 12, 39, 35, 553000), 'Youtube'),
 (datetime.datetime(2019, 5, 30, 17, 23, 10), 'Facebook'),
 (datetime.datetime(2019, 5, 31, 12, 18, 30, 467000), 'Youtube'),
 (datetime.datetime(2019, 6, 1, 12, 53, 38, 227000), 'Naver'),
 (datetime.datetime(2019, 6, 1, 18, 59, 41), 'Instagram'),
 (datetime.datetime(2019, 6, 2, 13, 19, 44, 780000), 'Facebook'),
 (datetime.datetime(2019, 6, 2, 15, 16, 57), 'Instagram'),
 (datetime.datetime(2019, 6, 3, 12, 29, 39, 157000), 'Google'),
 (datetime.datetime(2019, 6, 4, 13, 11, 34, 537000), 'Organic'),
 (datetime.datetime(2019, 6, 5, 12, 39, 54, 320000), 'Youtube'),
 (datetime.datetime(2019, 6, 6, 12, 35, 31, 260000), 'Instagram'),
 (datetime.datetime(2019, 6, 7, 14, 13, 30, 970000), 'Google'),
 (datetime.datetime(2019, 6, 8, 12, 58, 44, 550000), 'Organic'),
 (datetime.datetime(2019, 6, 9, 12, 58, 28, 37000), 'Naver'),
 (datetime.datetime(2019, 6, 10, 13, 0, 17, 77000), 'Instagram'),
 (datetime.datetime(2019, 6, 10, 15, 2, 56, 180000), 'Instagram'),
 (datetime.datetime(2019, 6, 11, 13, 35, 18, 527000), 'Google'),
 (datetime.datetime(2019, 6, 12, 13, 13, 36, 663000), 'Organic'),
 (datetime.datetime(2019, 6, 13, 13, 31, 34, 237000), 'Organic'),
 (datetime.datetime(2019, 6, 14, 13, 19, 42, 297000), 'Organic'),
 (datetime.datetime(2019, 6, 14, 13, 24, 3, 453000), 'Youtube'),
 (datetime.datetime(2019, 6, 15, 13, 7, 3, 207000), 'Instagram'),
 (datetime.datetime(2019, 6, 16, 12, 44, 44, 787000), 'Google'),
 (datetime.datetime(2019, 6, 17, 13, 13, 3, 103000), 'Instagram'),
 (datetime.datetime(2019, 6, 18, 12, 33, 17, 483000), 'Instagram'),
 (datetime.datetime(2019, 6, 19, 12, 38, 26, 733000), 'Instagram'),
 (datetime.datetime(2019, 6, 20, 12, 50, 39, 390000), 'Youtube'),
 (datetime.datetime(2019, 6, 21, 12, 57, 52, 737000), 'Naver'),
 (datetime.datetime(2019, 6, 22, 13, 21, 12, 57000), 'Naver'),
 (datetime.datetime(2019, 6, 22, 16, 4, 40), 'Naver'),
 (datetime.datetime(2019, 6, 23, 12, 33, 2, 350000), 'Facebook'),
 (datetime.datetime(2019, 6, 24, 12, 20, 55, 627000), 'Naver'),
 (datetime.datetime(2019, 6, 25, 12, 53, 30, 443000), 'Organic'),
 (datetime.datetime(2019, 6, 26, 12, 16, 51, 993000), 'Facebook'),
 (datetime.datetime(2019, 6, 26, 18, 36, 54), 'Facebook'),
 (datetime.datetime(2019, 6, 27, 13, 50, 9, 650000), 'Google'),
 (datetime.datetime(2019, 6, 28, 13, 15, 23, 967000), 'Youtube'),
 (datetime.datetime(2019, 6, 29, 13, 38, 34, 300000), 'Instagram'),
 (datetime.datetime(2019, 6, 29, 13, 42, 47, 183000), 'Google'),
 (datetime.datetime(2019, 6, 29, 13, 43, 52, 563000), 'Google'),
 (datetime.datetime(2019, 6, 30, 12, 45, 5, 493000), 'Organic'),
 (datetime.datetime(2019, 7, 1, 12, 27, 32, 790000), 'Instagram'),
 (datetime.datetime(2019, 7, 1, 17, 58, 15), 'Instagram'),
 (datetime.datetime(2019, 7, 2, 13, 19, 33, 543000), 'Facebook'),
 (datetime.datetime(2019, 7, 2, 14, 56, 39, 963000), 'Organic'),
 (datetime.datetime(2019, 7, 3, 12, 48, 27, 257000), 'Organic'),
 (datetime.datetime(2019, 7, 8, 12, 53, 49, 693000), 'Organic'),
 (datetime.datetime(2019, 7, 9, 12, 21, 37, 27000), 'Organic'),
 (datetime.datetime(2019, 7, 10, 12, 41, 56, 653000), 'Instagram'),
 (datetime.datetime(2019, 7, 11, 13, 2, 33, 940000), 'Youtube'),
 (datetime.datetime(2019, 7, 12, 12, 39, 45, 390000), 'Naver'),
 (datetime.datetime(2019, 7, 13, 13, 16, 19, 803000), 'Youtube'),
 (datetime.datetime(2019, 7, 13, 13, 19, 5, 797000), 'Youtube'),
 (datetime.datetime(2019, 7, 14, 14, 34, 33, 657000), 'Youtube'),
 (datetime.datetime(2019, 7, 17, 12, 44, 32, 63000), 'Organic'),
 (datetime.datetime(2019, 7, 17, 16, 53, 22), 'Google'),
 (datetime.datetime(2019, 7, 18, 12, 51, 54, 643000), 'Youtube'),
 (datetime.datetime(2019, 7, 18, 12, 56, 43, 577000), 'Youtube'),
 (datetime.datetime(2019, 7, 18, 20, 29, 57), 'Youtube'),
 (datetime.datetime(2019, 7, 19, 16, 1, 16, 17000), 'Naver'),
 (datetime.datetime(2019, 7, 19, 17, 38, 53), 'Organic'),
 (datetime.datetime(2019, 7, 19, 17, 40, 18), 'Instagram'),
 (datetime.datetime(2019, 7, 19, 17, 41, 51), 'Instagram'),
 (datetime.datetime(2019, 7, 19, 17, 43, 51), 'Youtube'),
 (datetime.datetime(2019, 7, 20, 12, 57, 48, 747000), 'Naver'),
 (datetime.datetime(2019, 7, 20, 13, 1, 13, 857000), 'Instagram'),
 (datetime.datetime(2019, 7, 21, 12, 53, 14, 990000), 'Instagram'),
 (datetime.datetime(2019, 7, 22, 13, 19, 23, 447000), 'Youtube'),
 (datetime.datetime(2019, 7, 23, 12, 47, 7, 460000), 'Naver'),
 (datetime.datetime(2019, 7, 24, 12, 54, 51, 497000), 'Google'),
 (datetime.datetime(2019, 7, 24, 16, 8, 42), 'Google'),
 (datetime.datetime(2019, 7, 25, 12, 34, 51, 103000), 'Instagram'),
 (datetime.datetime(2019, 7, 25, 12, 39, 35, 593000), 'Instagram'),
 (datetime.datetime(2019, 7, 26, 12, 47, 35, 500000), 'Instagram'),
 (datetime.datetime(2019, 7, 26, 12, 52, 22, 50000), 'Organic'),
 (datetime.datetime(2019, 7, 26, 19, 18, 38), 'Google'),
 (datetime.datetime(2019, 7, 27, 13, 33, 2, 323000), 'Google'),
 (datetime.datetime(2019, 7, 29, 13, 6, 27, 130000), 'Facebook'),
 (datetime.datetime(2019, 7, 30, 12, 23, 24, 593000), 'Google'),
 (datetime.datetime(2019, 7, 30, 15, 31, 25), 'Instagram'),
 (datetime.datetime(2019, 7, 31, 13, 38, 48, 527000), 'Facebook'),
 (datetime.datetime(2019, 8, 1, 12, 56, 52, 543000), 'Google'),
 (datetime.datetime(2019, 8, 2, 13, 32, 39, 743000), 'Naver'),
 (datetime.datetime(2019, 8, 3, 14, 2, 1, 400000), 'Youtube'),
 (datetime.datetime(2019, 8, 4, 13, 53, 54, 553000), 'Instagram'),
 (datetime.datetime(2019, 8, 5, 12, 37, 58, 720000), 'Organic'),
 (datetime.datetime(2019, 8, 6, 12, 47, 42, 17000), 'Youtube'),
 (datetime.datetime(2019, 8, 7, 12, 42, 7, 713000), 'Facebook'),
 (datetime.datetime(2019, 8, 8, 12, 7, 18, 430000), 'Instagram'),
 (datetime.datetime(2019, 8, 9, 13, 19, 19, 580000), 'Organic'),
 (datetime.datetime(2019, 8, 10, 14, 3, 46, 323000), 'Organic'),
 (datetime.datetime(2019, 8, 11, 13, 57, 58, 377000), 'Naver'),
 (datetime.datetime(2019, 8, 12, 12, 46, 55, 367000), 'Instagram'),
 (datetime.datetime(2019, 8, 13, 12, 22, 28, 127000), 'Instagram'),
 (datetime.datetime(2019, 8, 14, 12, 10, 21, 790000), 'Instagram'),
 (datetime.datetime(2019, 8, 15, 17, 28, 48, 497000), 'Naver'),
 (datetime.datetime(2019, 8, 16, 13, 54, 53, 113000), 'Instagram'),
 (datetime.datetime(2019, 8, 17, 14, 11, 54, 877000), 'Instagram'),
 (datetime.datetime(2019, 8, 18, 13, 38, 14, 420000), 'Organic'),
 (datetime.datetime(2019, 8, 19, 13, 24, 12, 170000), 'Youtube'),
 (datetime.datetime(2019, 8, 20, 13, 33, 0, 347000), 'Facebook'),
 (datetime.datetime(2019, 8, 21, 13, 34, 23, 947000), 'Facebook'),
 (datetime.datetime(2019, 8, 21, 13, 37, 4, 953000), 'Google'),
 (datetime.datetime(2019, 8, 22, 12, 36, 23, 127000), 'Google'),
 (datetime.datetime(2019, 8, 23, 14, 0, 1, 60000), 'Facebook'),
 (datetime.datetime(2019, 8, 25, 14, 58, 40, 387000), 'Organic'),
 (datetime.datetime(2019, 8, 26, 13, 41, 51, 137000), 'Naver'),
 (datetime.datetime(2019, 8, 27, 12, 21, 19, 190000), 'Naver'),
 (datetime.datetime(2019, 8, 28, 13, 2, 15, 903000), 'Naver'),
 (datetime.datetime(2019, 8, 28, 13, 4, 53, 717000), 'Youtube'),
 (datetime.datetime(2019, 8, 29, 12, 17, 3, 380000), 'Organic'),
 (datetime.datetime(2019, 9, 3, 14, 46, 40, 353000), 'Organic'),
 (datetime.datetime(2019, 9, 3, 16, 11, 29), 'Facebook'),
 (datetime.datetime(2019, 9, 3, 16, 12, 24), 'Google'),
 (datetime.datetime(2019, 9, 4, 12, 59, 13, 917000), 'Naver'),
 (datetime.datetime(2019, 9, 5, 12, 35, 33, 793000), 'Facebook'),
 (datetime.datetime(2019, 9, 6, 13, 29, 40, 160000), 'Instagram'),
 (datetime.datetime(2019, 9, 6, 18, 53, 41, 373000), 'Google'),
 (datetime.datetime(2019, 9, 7, 14, 50, 41, 860000), 'Instagram'),
 (datetime.datetime(2019, 9, 8, 13, 44, 0, 730000), 'Instagram'),
 (datetime.datetime(2019, 9, 9, 12, 30, 40, 303000), 'Naver'),
 (datetime.datetime(2019, 9, 10, 12, 56, 17, 543000), 'Facebook'),
 (datetime.datetime(2019, 9, 11, 13, 9, 50, 40000), 'Google'),
 (datetime.datetime(2019, 9, 12, 13, 34, 36, 337000), 'Facebook'),
 (datetime.datetime(2019, 9, 13, 13, 18, 58, 977000), 'Instagram'),
 (datetime.datetime(2019, 9, 14, 13, 43, 47, 3000), 'Naver'),
 (datetime.datetime(2019, 9, 15, 13, 40, 54, 840000), 'Organic'),
 (datetime.datetime(2019, 9, 16, 13, 39, 13, 283000), 'Organic'),
 (datetime.datetime(2019, 9, 17, 12, 23, 56, 137000), 'Youtube'),
 (datetime.datetime(2019, 9, 18, 13, 37, 0, 210000), 'Naver'),
 (datetime.datetime(2019, 9, 19, 13, 51, 55, 193000), 'Organic'),
 (datetime.datetime(2019, 9, 20, 13, 52, 45, 850000), 'Naver'),
 (datetime.datetime(2019, 9, 22, 14, 41, 19, 317000), 'Facebook'),
 (datetime.datetime(2019, 9, 23, 12, 43, 30, 643000), 'Organic'),
 (datetime.datetime(2019, 9, 24, 15, 4, 54, 267000), 'Instagram'),
 (datetime.datetime(2019, 9, 25, 13, 29, 38, 347000), 'Instagram'),
 (datetime.datetime(2019, 9, 27, 13, 13, 26, 970000), 'Organic'),
 (datetime.datetime(2019, 9, 29, 14, 1, 37, 303000), 'Instagram'),
 (datetime.datetime(2019, 9, 30, 13, 30, 34, 823000), 'Naver'),
 (datetime.datetime(2019, 10, 2, 14, 51, 24, 390000), 'Youtube'),
 (datetime.datetime(2019, 10, 3, 14, 57, 24, 417000), 'Organic'),
 (datetime.datetime(2019, 10, 3, 18, 15, 4, 250000), 'Instagram'),
 (datetime.datetime(2019, 10, 3, 19, 56, 38), 'Youtube'),
 (datetime.datetime(2019, 10, 4, 15, 31, 35, 587000), 'Youtube'),
 (datetime.datetime(2019, 10, 5, 15, 6, 28, 717000), 'Youtube'),
 (datetime.datetime(2019, 10, 7, 13, 0, 30, 950000), 'Naver'),
 (datetime.datetime(2019, 10, 8, 12, 52, 10, 823000), 'Instagram'),
 (datetime.datetime(2019, 10, 9, 14, 13, 5, 130000), 'Instagram'),
 (datetime.datetime(2019, 10, 13, 15, 57, 9, 387000), 'Naver'),
 (datetime.datetime(2019, 10, 14, 17, 7, 54, 133000), 'Google'),
 (datetime.datetime(2019, 10, 15, 12, 57, 35, 127000), 'Instagram'),
 (datetime.datetime(2019, 10, 16, 14, 1, 36, 993000), 'Instagram'),
 (datetime.datetime(2019, 10, 17, 12, 35, 49, 640000), 'Google'),
 (datetime.datetime(2019, 10, 18, 14, 29, 12, 150000), 'Instagram'),
 (datetime.datetime(2019, 10, 20, 14, 23, 12, 523000), 'Youtube'),
 (datetime.datetime(2019, 10, 21, 13, 6, 43, 27000), 'Naver'),
 (datetime.datetime(2019, 10, 22, 13, 21, 42, 390000), 'Organic'),
 (datetime.datetime(2019, 10, 23, 13, 42, 59, 783000), 'Youtube'),
 (datetime.datetime(2019, 10, 23, 20, 16, 21), 'Youtube'),
 (datetime.datetime(2019, 10, 24, 13, 19, 58, 673000), 'Google'),
 (datetime.datetime(2019, 10, 27, 12, 55, 38, 563000), 'Instagram'),
 (datetime.datetime(2019, 10, 28, 15, 23, 22, 480000), 'Google'),
 (datetime.datetime(2019, 10, 29, 13, 41, 50, 303000), 'Naver'),
 (datetime.datetime(2019, 10, 29, 13, 42, 40, 357000), 'Naver'),
 (datetime.datetime(2019, 10, 29, 13, 47, 47, 353000), 'Facebook'),
 (datetime.datetime(2019, 10, 30, 15, 56, 53, 263000), 'Youtube'),
 (datetime.datetime(2019, 10, 31, 13, 59, 2, 907000), 'Naver'),
 (datetime.datetime(2019, 11, 5, 16, 29, 17, 403000), 'Youtube'),
 (datetime.datetime(2019, 11, 6, 13, 12, 22, 887000), 'Organic'),
 (datetime.datetime(2019, 11, 7, 14, 13, 54, 197000), 'Organic'),
 (datetime.datetime(2019, 11, 8, 14, 52, 52, 620000), 'Youtube'),
 (datetime.datetime(2019, 11, 8, 14, 56, 39, 267000), 'Youtube'),
 (datetime.datetime(2019, 11, 9, 15, 23, 15, 843000), 'Youtube'),
 (datetime.datetime(2019, 11, 10, 15, 49, 40, 190000), 'Organic'),
 (datetime.datetime(2019, 11, 11, 14, 7, 44, 547000), 'Instagram'),
 (datetime.datetime(2019, 11, 14, 15, 33, 8, 933000), 'Google'),
 (datetime.datetime(2019, 11, 14, 15, 38, 15, 263000), 'Organic'),
 (datetime.datetime(2019, 11, 17, 14, 36, 52), 'Youtube'),
 (datetime.datetime(2019, 11, 18, 16, 24, 2), 'Facebook'),
 (datetime.datetime(2019, 11, 19, 16, 28, 12), 'Youtube'),
 (datetime.datetime(2019, 11, 20, 15, 41, 25), 'Google'),
 (datetime.datetime(2019, 11, 21, 15, 44, 1), 'Naver'),
 (datetime.datetime(2019, 11, 22, 17, 55, 35), 'Facebook'),
 (datetime.datetime(2019, 11, 23, 15, 34, 30), 'Google'),
 (datetime.datetime(2019, 11, 25, 14, 31, 24), 'Organic'),
 (datetime.datetime(2019, 11, 26, 16, 54, 19), 'Google')]

### UNION과 UNION ALL 차이점 이해하기

In [57]:
%%sql
-- 중복된것을 하나만 보여줌
SELECT 'keeyong' as first_name, 'han' as last_name

UNION

SELECT 'elon', 'musk'

UNION

SELECT 'keeyong', 'han'

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
2 rows affected.

[('elon', 'musk'), ('keeyong', 'han')]

In [58]:
%%sql
-- 중복된것을 다 return함
SELECT 'keeyong' as first_name, 'han' as last_name

UNION ALL

SELECT 'elon', 'musk'

UNION ALL

SELECT 'keeyong', 'han'

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
3 rows affected.

[('keeyong', 'han'), ('elon', 'musk'), ('keeyong', 'han')]

## JOIN:

An SQL JOIN clause is used to combine rows from two or more tables, based on a common field between them.

왼쪽 테이블을 LEFT라고 하고 오른쪽 테이블을 RIGHT이라고 하자. JOIN의 결과는 방식에 상관없이 양쪽의 필드를 모두 가진 새로운 테이블을 만들어내게 됨. 조인의 방식에 따라 다음 두 가지가 달라짐:

1. 어떤 레코드들이 선택되는지?
2. 어떤 필드들이 채워지는지?

In [59]:
%%sql

DROP TABLE IF EXISTS wmfrlek99.vital;
CREATE TABLE wmfrlek99.vital (
    UserID int,
    VitalID	int,
    Date date,
    Weight int
);
INSERT INTO wmfrlek99.vital VALUES
(100,	1, '2020-01-01', 75),
(100, 3, '2020-01-02', 78),
(101, 2, '2020-01-01', 90),
(101, 4, '2020-01-02', 95);

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.
Done.
4 rows affected.

[]

In [60]:
%%sql

DROP TABLE IF EXISTS wmfrlek99.alert;
CREATE TABLE wmfrlek99.alert (
    AlertID int,
    VitalID	int,
    AlertType varchar(32),
    Date date,
    UserID int
);
INSERT INTO wmfrlek99.alert VALUES
 (1,	4, 'WeightIncrease', '2020-01-01', 101),
 (2, NULL, 'MissingVital', '2020-01-04', 100),
 (3, NULL, 'MissingVital', '2020-01-04', 101);

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.
Done.
3 rows affected.

[]

* INNER JOIN
1. 양쪽 테이블에서 매치가 되는 레코드들만 리턴함
2. 양쪽 테이블의 필드가 모두 채워진 상태로 리턴됨

In [61]:
%%sql

SELECT * FROM wmfrlek99.Vital v
JOIN wmfrlek99.Alert a ON v.vitalID = a.vitalID;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(101, 4, datetime.date(2020, 1, 2), 95, 1, 4, 'WeightIncrease', datetime.date(2020, 1, 1), 101)]

* LEFT JOIN: 
1. 왼쪽 테이블의 레코드는 모두 리턴되며 오른쪽 테이블과 매칭이 되는 레코드들의 경우에는 오른쪽 테이블 레코드들의 컬럼들이 채워진 상태로 리턴됨.
2. 매칭이 안되는 왼쪽 테이블 레코드들은 오른쪽 테이블에서 들어오는 필드들은 NULL로 채워짐

In [62]:
%%sql

SELECT * FROM wmfrlek99.Vital v
LEFT JOIN wmfrlek99.Alert a ON v.vitalID = a.vitalID;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
4 rows affected.

[(100, 1, datetime.date(2020, 1, 1), 75, None, None, None, None, None),
 (100, 3, datetime.date(2020, 1, 2), 78, None, None, None, None, None),
 (101, 2, datetime.date(2020, 1, 1), 90, None, None, None, None, None),
 (101, 4, datetime.date(2020, 1, 2), 95, 1, 4, 'WeightIncrease', datetime.date(2020, 1, 1), 101)]

* FULL JOIN (OUTER JOIN):
1. 왼쪽 테이블과 오른쪽 테이블의 모든 레코드들을 리턴함
2. 매칭되는 경우에만 양쪽 테이블들의 모든 필드들이 채워진 상태로 리턴됨

In [63]:
%%sql

SELECT * FROM wmfrlek99.Vital v
FULL JOIN wmfrlek99.Alert a ON v.vitalID = a.vitalID;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
6 rows affected.

[(101, 4, datetime.date(2020, 1, 2), 95, 1, 4, 'WeightIncrease', datetime.date(2020, 1, 1), 101),
 (None, None, None, None, 2, None, 'MissingVital', datetime.date(2020, 1, 4), 100),
 (None, None, None, None, 3, None, 'MissingVital', datetime.date(2020, 1, 4), 101),
 (101, 2, datetime.date(2020, 1, 1), 90, None, None, None, None, None),
 (100, 1, datetime.date(2020, 1, 1), 75, None, None, None, None, None),
 (100, 3, datetime.date(2020, 1, 2), 78, None, None, None, None, None)]

* CARTESIAN JOIN (CROSS JOIN): 
1. 조인 조건 없이 두 개 테이블의 내용을 모두 조합한 결과 레코드들을 생성

In [64]:
%%sql

SELECT *
FROM (
    SELECT vitalid  -- 1,2,3,4
    FROM wmfrlek99.vital
)
CROSS JOIN (
    SELECT alertid   -- 1,2,3
    FROM wmfrlek99.alert
);

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
12 rows affected.

[(1, 1),
 (1, 2),
 (1, 3),
 (3, 1),
 (3, 2),
 (3, 3),
 (2, 1),
 (2, 2),
 (2, 3),
 (4, 1),
 (4, 2),
 (4, 3)]

In [65]:
%%sql

SELECT * FROM wmfrlek99.Vital v
CROSS JOIN wmfrlek99.Alert a;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
12 rows affected.

[(100, 1, datetime.date(2020, 1, 1), 75, 1, 4, 'WeightIncrease', datetime.date(2020, 1, 1), 101),
 (100, 3, datetime.date(2020, 1, 2), 78, 1, 4, 'WeightIncrease', datetime.date(2020, 1, 1), 101),
 (101, 2, datetime.date(2020, 1, 1), 90, 1, 4, 'WeightIncrease', datetime.date(2020, 1, 1), 101),
 (101, 4, datetime.date(2020, 1, 2), 95, 1, 4, 'WeightIncrease', datetime.date(2020, 1, 1), 101),
 (100, 1, datetime.date(2020, 1, 1), 75, 2, None, 'MissingVital', datetime.date(2020, 1, 4), 100),
 (100, 3, datetime.date(2020, 1, 2), 78, 2, None, 'MissingVital', datetime.date(2020, 1, 4), 100),
 (101, 2, datetime.date(2020, 1, 1), 90, 2, None, 'MissingVital', datetime.date(2020, 1, 4), 100),
 (101, 4, datetime.date(2020, 1, 2), 95, 2, None, 'MissingVital', datetime.date(2020, 1, 4), 100),
 (100, 1, datetime.date(2020, 1, 1), 75, 3, None, 'MissingVital', datetime.date(2020, 1, 4), 101),
 (100, 3, datetime.date(2020, 1, 2), 78, 3, None, 'MissingVital', datetime.date(2020, 1, 4), 101),
 (101, 2, datetime.date(2020, 1, 1), 90, 3, None, 'MissingVital', datetime.date(2020, 1, 4), 101),
 (101, 4, datetime.date(2020, 1, 2), 95, 3, None, 'MissingVital', datetime.date(2020, 1, 4), 101)]

* Self-Join

In [66]:
%%sql
-- 같은 테이블을 inner join을 한 결과
SELECT * FROM wmfrlek99.Vital v1
JOIN wmfrlek99.Vital v2 ON v1.vitalID = v2.vitalID;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
4 rows affected.

[(100, 1, datetime.date(2020, 1, 1), 75, 100, 1, datetime.date(2020, 1, 1), 75),
 (100, 3, datetime.date(2020, 1, 2), 78, 100, 3, datetime.date(2020, 1, 2), 78),
 (101, 2, datetime.date(2020, 1, 1), 90, 101, 2, datetime.date(2020, 1, 1), 90),
 (101, 4, datetime.date(2020, 1, 2), 95, 101, 4, datetime.date(2020, 1, 2), 95)]

Assignment 2: 사용자별로 처음과 마지막 채널
알아내기

* 숙제 제출 포맷 (모든 사용자에 대해)
  * 사용자ID, 첫번째 채널, 마지막 채널

* ROW_NUMBER vs. FIRST_VALUE/LAST_VALUE
* 사용자 251번의 시간순으로 봤을 때 첫 번째 채널과 마지막 채널은 무엇인가?
  * 노가다를 하자면 아래 쿼리를 실행해서 처음과 마지막 채널을 보면 된다.

  SELECT ts, channel</br>
  FROM raw_data.user_session_channel usc</br>
  JOIN raw_data.session_timestamp st ON usc.sessionid = st.sessionid
  </br>WHERE userid = 251
  </br>ORDER BY 1;

* ROW_NUMBER 이용해서 해보자
  * ROW_NUMBER() OVER (PARTITION BY field1 ORDER BY field2) nn

In [69]:
%%sql

WITH cte AS(
  SELECT userid, channel,(ROW_NUMBER() OVER (Partition BY usc.userid ORDER BY st.ts asc))
  AS arn, (ROW_NUMBER() OVER (Partition BY usc.userid ORDER BY st.ts desc)) as drn
  FROM raw_data.user_session_channel usc
  JOIN raw_data.session_timestamp st ON usc.sessionid = st.sessionid
)
SELECT cte1.userid, cte1.channel AS first_touch, cte2.channel AS last_touch
FROM cte cte1
JOIN cte cte2 ON cte1.userid = cte2.userid
WHERE cte1.arn = 1 and cte2.drn = 1
order by 1;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
949 rows affected.

[(27, 'Youtube', 'Instagram'),
 (29, 'Naver', 'Naver'),
 (33, 'Google', 'Youtube'),
 (34, 'Youtube', 'Naver'),
 (36, 'Naver', 'Youtube'),
 (40, 'Youtube', 'Google'),
 (41, 'Facebook', 'Youtube'),
 (44, 'Naver', 'Instagram'),
 (45, 'Youtube', 'Instagram'),
 (59, 'Instagram', 'Instagram'),
 (64, 'Youtube', 'Youtube'),
 (65, 'Youtube', 'Organic'),
 (68, 'Youtube', 'Organic'),
 (69, 'Facebook', 'Instagram'),
 (80, 'Organic', 'Naver'),
 (84, 'Google', 'Youtube'),
 (87, 'Youtube', 'Google'),
 (97, 'Organic', 'Organic'),
 (112, 'Facebook', 'Youtube'),
 (113, 'Organic', 'Organic'),
 (114, 'Instagram', 'Youtube'),
 (117, 'Organic', 'Youtube'),
 (163, 'Google', 'Naver'),
 (173, 'Google', 'Organic'),
 (181, 'Facebook', 'Instagram'),
 (184, 'Youtube', 'Youtube'),
 (187, 'Organic', 'Youtube'),
 (191, 'Naver', 'Instagram'),
 (192, 'Facebook', 'Google'),
 (193, 'Google', 'Facebook'),
 (196, 'Facebook', 'Naver'),
 (197, 'Naver', 'Youtube'),
 (198, 'Facebook', 'Google'),
 (199, 'Naver', 'Instagram'),
 (201, 'Instagram', 'Youtube'),
 (203, 'Naver', 'Facebook'),
 (204, 'Naver', 'Youtube'),
 (207, 'Facebook', 'Youtube'),
 (210, 'Google', 'Google'),
 (213, 'Naver', 'Organic'),
 (216, 'Instagram', 'Naver'),
 (218, 'Google', 'Youtube'),
 (222, 'Facebook', 'Google'),
 (223, 'Youtube', 'Facebook'),
 (225, 'Facebook', 'Naver'),
 (226, 'Organic', 'Instagram'),
 (227, 'Google', 'Google'),
 (229, 'Google', 'Facebook'),
 (230, 'Naver', 'Google'),
 (231, 'Naver', 'Instagram'),
 (232, 'Instagram', 'Naver'),
 (233, 'Facebook', 'Organic'),
 (236, 'Naver', 'Youtube'),
 (237, 'Organic', 'Google'),
 (240, 'Organic', 'Organic'),
 (243, 'Youtube', 'Instagram'),
 (246, 'Organic', 'Google'),
 (248, 'Naver', 'Instagram'),
 (250, 'Instagram', 'Facebook'),
 (251, 'Facebook', 'Google'),
 (253, 'Facebook', 'Youtube'),
 (254, 'Facebook', 'Facebook'),
 (255, 'Facebook', 'Instagram'),
 (256, 'Naver', 'Instagram'),
 (257, 'Instagram', 'Organic'),
 (258, 'Google', 'Facebook'),
 (259, 'Google', 'Naver'),
 (260, 'Naver', 'Youtube'),
 (262, 'Organic', 'Instagram'),
 (264, 'Google', 'Facebook'),
 (265, 'Facebook', 'Instagram'),
 (266, 'Google', 'Instagram'),
 (267, 'Instagram', 'Naver'),
 (269, 'Facebook', 'Organic'),
 (270, 'Facebook', 'Youtube'),
 (272, 'Naver', 'Naver'),
 (277, 'Naver', 'Naver'),
 (278, 'Naver', 'Organic'),
 (280, 'Google', 'Organic'),
 (282, 'Naver', 'Facebook'),
 (301, 'Naver', 'Facebook'),
 (329, 'Naver', 'Youtube'),
 (341, 'Naver', 'Facebook'),
 (345, 'Google', 'Organic'),
 (355, 'Google', 'Naver'),
 (363, 'Naver', 'Facebook'),
 (368, 'Organic', 'Youtube'),
 (369, 'Youtube', 'Organic'),
 (371, 'Google', 'Google'),
 (385, 'Instagram', 'Organic'),
 (409, 'Facebook', 'Organic'),
 (420, 'Youtube', 'Facebook'),
 (437, 'Organic', 'Instagram'),
 (465, 'Organic', 'Youtube'),
 (468, 'Instagram', 'Facebook'),
 (473, 'Youtube', 'Naver'),
 (474, 'Facebook', 'Naver'),
 (494, 'Youtube', 'Facebook'),
 (510, 'Naver', 'Facebook'),
 (511, 'Google', 'Google'),
 (533, 'Instagram', 'Google'),
 (538, 'Youtube', 'Organic'),
 (543, 'Naver', 'Instagram'),
 (572, 'Organic', 'Naver'),
 (586, 'Naver', 'Organic'),
 (587, 'Youtube', 'Google'),
 (599, 'Organic', 'Google'),
 (626, 'Facebook', 'Google'),
 (643, 'Facebook', 'Facebook'),
 (645, 'Youtube', 'Organic'),
 (654, 'Naver', 'Naver'),
 (656, 'Google', 'Youtube'),
 (661, 'Youtube', 'Google'),
 (676, 'Instagram', 'Facebook'),
 (682, 'Organic', 'Facebook'),
 (683, 'Youtube', 'Youtube'),
 (686, 'Instagram', 'Organic'),
 (694, 'Google', 'Organic'),
 (698, 'Organic', 'Facebook'),
 (699, 'Youtube', 'Organic'),
 (700, 'Instagram', 'Organic'),
 (702, 'Instagram', 'Youtube'),
 (706, 'Youtube', 'Facebook'),
 (707, 'Facebook', 'Facebook'),
 (708, 'Organic', 'Instagram'),
 (710, 'Youtube', 'Organic'),
 (711, 'Organic', 'Naver'),
 (712, 'Organic', 'Google'),
 (715, 'Instagram', 'Naver'),
 (732, 'Organic', 'Facebook'),
 (735, 'Organic', 'Google'),
 (738, 'Google', 'Google'),
 (744, 'Facebook', 'Naver'),
 (750, 'Facebook', 'Google'),
 (752, 'Organic', 'Facebook'),
 (757, 'Google', 'Google'),
 (763, 'Naver', 'Youtube'),
 (765, 'Naver', 'Naver'),
 (768, 'Organic', 'Youtube'),
 (771, 'Facebook', 'Organic'),
 (772, 'Youtube', 'Instagram'),
 (774, 'Facebook', 'Naver'),
 (778, 'Instagram', 'Instagram'),
 (779, 'Instagram', 'Naver'),
 (780, 'Instagram', 'Naver'),
 (782, 'Google', 'Google'),
 (785, 'Organic', 'Facebook'),
 (786, 'Youtube', 'Naver'),
 (787, 'Organic', 'Naver'),
 (788, 'Naver', 'Facebook'),
 (789, 'Google', 'Instagram'),
 (790, 'Facebook', 'Google'),
 (793, 'Organic', 'Organic'),
 (795, 'Google', 'Google'),
 (801, 'Facebook', 'Google'),
 (803, 'Instagram', 'Organic'),
 (805, 'Instagram', 'Facebook'),
 (808, 'Organic', 'Facebook'),
 (810, 'Instagram', 'Naver'),
 (812, 'Google', 'Facebook'),
 (822, 'Organic', 'Organic'),
 (825, 'Naver', 'Google'),
 (830, 'Organic', 'Instagram'),
 (832, 'Youtube', 'Facebook'),
 (836, 'Instagram', 'Facebook'),
 (841, 'Naver', 'Organic'),
 (845, 'Youtube', 'Facebook'),
 (847, 'Google', 'Facebook'),
 (849, 'Facebook', 'Google'),
 (852, 'Google', 'Organic'),
 (855, 'Naver', 'Naver'),
 (858, 'Organic', 'Instagram'),
 (867, 'Naver', 'Youtube'),
 (873, 'Instagram', 'Naver'),
 (876, 'Naver', 'Organic'),
 (879, 'Facebook', 'Youtube'),
 (881, 'Youtube', 'Youtube'),
 (887, 'Facebook', 'Facebook'),
 (889, 'Organic', 'Instagram'),
 (891, 'Google', 'Youtube'),
 (895, 'Youtube', 'Instagram'),
 (897, 'Facebook', 'Organic'),
 (899, 'Instagram', 'Instagram'),
 (901, 'Youtube', 'Youtube'),
 (905, 'Youtube', 'Instagram'),
 (907, 'Naver', 'Naver'),
 (909, 'Naver', 'Facebook'),
 (911, 'Google', 'Facebook'),
 (913, 'Organic', 'Naver'),
 (917, 'Facebook', 'Youtube'),
 (919, 'Naver', 'Instagram'),
 (921, 'Organic', 'Facebook'),
 (923, 'Organic', 'Facebook'),
 (927, 'Naver', 'Organic'),
 (929, 'Naver', 'Naver'),
 (931, 'Youtube', 'Naver'),
 (935, 'Organic', 'Facebook'),
 (937, 'Instagram', 'Google'),
 (939, 'Youtube', 'Instagram'),
 (943, 'Naver', 'Google'),
 (945, 'Naver', 'Facebook'),
 (947, 'Naver', 'Youtube'),
 (949, 'Instagram', 'Instagram'),
 (951, 'Naver', 'Google'),
 (953, 'Google', 'Organic'),
 (955, 'Youtube', 'Google'),
 (957, 'Google', 'Youtube'),
 (961, 'Facebook', 'Youtube'),
 (963, 'Youtube', 'Naver'),
 (965, 'Facebook', 'Organic'),
 (967, 'Facebook', 'Organic'),
 (969, 'Instagram', 'Organic'),
 (971, 'Naver', 'Facebook'),
 (973, 'Organic', 'Facebook'),
 (975, 'Youtube', 'Facebook'),
 (977, 'Youtube', 'Facebook'),
 (979, 'Organic', 'Naver'),
 (981, 'Naver', 'Naver'),
 (983, 'Instagram', 'Organic'),
 (985, 'Google', 'Organic'),
 (987, 'Youtube', 'Google'),
 (989, 'Facebook', 'Naver'),
 (993, 'Naver', 'Google'),
 (995, 'Organic', 'Organic'),
 (997, 'Google', 'Instagram'),
 (998, 'Naver', 'Naver'),
 (1001, 'Google', 'Youtube'),
 (1003, 'Instagram', 'Google'),
 (1005, 'Google', 'Organic'),
 (1007, 'Youtube', 'Google'),
 (1009, 'Youtube', 'Google'),
 (1011, 'Google', 'Instagram'),
 (1013, 'Facebook', 'Youtube'),
 (1015, 'Naver', 'Naver'),
 (1023, 'Instagram', 'Naver'),
 (1027, 'Organic', 'Facebook'),
 (1029, 'Organic', 'Organic'),
 (1031, 'Organic', 'Naver'),
 (1033, 'Youtube', 'Instagram'),
 (1035, 'Instagram', 'Instagram'),
 (1037, 'Organic', 'Google'),
 (1039, 'Organic', 'Naver'),
 (1041, 'Organic', 'Google'),
 (1043, 'Organic', 'Instagram'),
 (1045, 'Youtube', 'Google'),
 (1047, 'Naver', 'Facebook'),
 (1049, 'Naver', 'Youtube'),
 (1051, 'Naver', 'Facebook'),
 (1053, 'Youtube', 'Organic'),
 (1055, 'Google', 'Instagram'),
 (1059, 'Organic', 'Facebook'),
 (1063, 'Google', 'Instagram'),
 (1065, 'Facebook', 'Facebook'),
 (1067, 'Google', 'Naver'),
 (1069, 'Naver', 'Facebook'),
 (1073, 'Google', 'Youtube'),
 (1075, 'Organic', 'Facebook'),
 (1079, 'Naver', 'Facebook'),
 (1081, 'Facebook', 'Youtube'),
 (1083, 'Naver', 'Google'),
 (1085, 'Organic', 'Youtube'),
 (1087, 'Facebook', 'Google'),
 (1089, 'Organic', 'Youtube'),
 (1091, 'Facebook', 'Instagram'),
 (1093, 'Youtube', 'Youtube'),
 (1095, 'Google', 'Organic'),
 (1099, 'Naver', 'Instagram'),
 (1103, 'Google', 'Instagram'),
 (1105, 'Google', 'Google'),
 (1109, 'Google', 'Google'),
 (1111, 'Facebook', 'Youtube'),
 (1115, 'Google', 'Google'),
 (1117, 'Instagram', 'Organic'),
 (1119, 'Google', 'Instagram'),
 (1121, 'Google', 'Google'),
 (1125, 'Naver', 'Instagram'),
 (1127, 'Instagram', 'Facebook'),
 (1133, 'Google', 'Facebook'),
 (1135, 'Youtube', 'Naver'),
 (1137, 'Facebook', 'Naver'),
 (1139, 'Youtube', 'Organic'),
 (1141, 'Google', 'Facebook'),
 (1145, 'Youtube', 'Google'),
 (1151, 'Google', 'Organic'),
 (1153, 'Youtube', 'Google'),
 (1155, 'Facebook', 'Naver'),
 (1157, 'Google', 'Google'),
 (1159, 'Organic', 'Google'),
 (1163, 'Youtube', 'Naver'),
 (1165, 'Google', 'Google'),
 (1167, 'Youtube', 'Youtube'),
 (1169, 'Naver', 'Facebook'),
 (1171, 'Facebook', 'Naver'),
 (1175, 'Naver', 'Organic'),
 (1177, 'Naver', 'Instagram'),
 (1179, 'Google', 'Google'),
 (1181, 'Youtube', 'Youtube'),
 (1183, 'Facebook', 'Google'),
 (1185, 'Instagram', 'Instagram'),
 (1187, 'Instagram', 'Instagram'),
 (1189, 'Facebook', 'Facebook'),
 (1191, 'Organic', 'Youtube'),
 (1193, 'Organic', 'Facebook'),
 (1195, 'Organic', 'Organic'),
 (1197, 'Instagram', 'Google'),
 (1199, 'Naver', 'Google'),
 (1203, 'Facebook', 'Google'),
 (1205, 'Organic', 'Instagram'),
 (1211, 'Youtube', 'Youtube'),
 (1213, 'Naver', 'Organic'),
 (1215, 'Facebook', 'Naver'),
 (1217, 'Youtube', 'Youtube'),
 (1219, 'Naver', 'Google'),
 (1221, 'Instagram', 'Organic'),
 (1223, 'Instagram', 'Google'),
 (1227, 'Naver', 'Youtube'),
 (1229, 'Google', 'Organic'),
 (1231, 'Organic', 'Organic'),
 (1233, 'Facebook', 'Naver'),
 (1237, 'Google', 'Facebook'),
 (1239, 'Google', 'Instagram'),
 (1241, 'Naver', 'Organic'),
 (1243, 'Instagram', 'Instagram'),
 (1245, 'Facebook', 'Facebook'),
 (1247, 'Facebook', 'Naver'),
 (1249, 'Organic', 'Naver'),
 (1251, 'Instagram', 'Facebook'),
 (1253, 'Google', 'Naver'),
 (1257, 'Google', 'Google'),
 (1259, 'Facebook', 'Facebook'),
 (1261, 'Instagram', 'Instagram'),
 (1263, 'Organic', 'Facebook'),
 (1265, 'Organic', 'Youtube'),
 (1269, 'Google', 'Organic'),
 (1273, 'Google', 'Google'),
 (1277, 'Instagram', 'Youtube'),
 (1279, 'Naver', 'Instagram'),
 (1281, 'Youtube', 'Google'),
 (1283, 'Youtube', 'Youtube'),
 (1285, 'Youtube', 'Organic'),
 (1287, 'Instagram', 'Organic'),
 (1289, 'Naver', 'Naver'),
 (1291, 'Instagram', 'Naver'),
 (1293, 'Google', 'Instagram'),
 (1295, 'Organic', 'Instagram'),
 (1297, 'Organic', 'Facebook'),
 (1299, 'Youtube', 'Organic'),
 (1301, 'Organic', 'Youtube'),
 (1303, 'Naver', 'Youtube'),
 (1305, 'Organic', 'Google'),
 (1307, 'Google', 'Naver'),
 (1309, 'Naver', 'Google'),
 (1311, 'Naver', 'Facebook'),
 (1313, 'Facebook', 'Naver'),
 (1315, 'Naver', 'Google'),
 (1317, 'Youtube', 'Organic'),
 (1319, 'Google', 'Youtube'),
 (1321, 'Google', 'Facebook'),
 (1325, 'Organic', 'Organic'),
 (1329, 'Organic', 'Naver'),
 (1331, 'Youtube', 'Google'),
 (1335, 'Youtube', 'Youtube'),
 (1337, 'Youtube', 'Instagram'),
 (1341, 'Facebook', 'Naver'),
 (1343, 'Naver', 'Youtube'),
 (1345, 'Instagram', 'Organic'),
 (1349, 'Organic', 'Instagram'),
 (1351, 'Naver', 'Google'),
 (1353, 'Naver', 'Facebook'),
 (1357, 'Instagram', 'Youtube'),
 (1361, 'Google', 'Facebook'),
 (1363, 'Organic', 'Google'),
 (1367, 'Instagram', 'Google'),
 (1369, 'Instagram', 'Facebook'),
 (1371, 'Naver', 'Naver'),
 (1375, 'Organic', 'Google'),
 (1377, 'Youtube', 'Youtube'),
 (1379, 'Organic', 'Google'),
 (1381, 'Google', 'Youtube'),
 (1383, 'Youtube', 'Google'),
 (1385, 'Google', 'Google'),
 (1387, 'Google', 'Google'),
 (1389, 'Google', 'Organic'),
 (1391, 'Youtube', 'Google'),
 (1393, 'Youtube', 'Organic'),
 (1395, 'Youtube', 'Facebook'),
 (1397, 'Instagram', 'Youtube'),
 (1399, 'Instagram', 'Instagram'),
 (1401, 'Organic', 'Google'),
 (1405, 'Youtube', 'Youtube'),
 (1409, 'Google', 'Organic'),
 (1411, 'Instagram', 'Google'),
 (1415, 'Google', 'Organic'),
 (1417, 'Naver', 'Naver'),
 (1419, 'Facebook', 'Instagram'),
 (1421, 'Organic', 'Naver'),
 (1425, 'Facebook', 'Youtube'),
 (1427, 'Youtube', 'Youtube'),
 (1429, 'Organic', 'Organic'),
 (1431, 'Instagram', 'Instagram'),
 (1433, 'Instagram', 'Naver'),
 (1435, 'Youtube', 'Facebook'),
 (1441, 'Naver', 'Google'),
 (1443, 'Google', 'Google'),
 (1445, 'Google', 'Facebook'),
 (1449, 'Facebook', 'Organic'),
 (1453, 'Facebook', 'Google'),
 (1455, 'Organic', 'Organic'),
 (1459, 'Google', 'Facebook'),
 (1461, 'Instagram', 'Youtube'),
 (1463, 'Youtube', 'Instagram'),
 (1465, 'Organic', 'Naver'),
 (1467, 'Google', 'Facebook'),
 (1469, 'Google', 'Naver'),
 (1471, 'Organic', 'Youtube'),
 (1473, 'Facebook', 'Naver'),
 (1475, 'Google', 'Facebook'),
 (1477, 'Organic', 'Google'),
 (1479, 'Youtube', 'Organic'),
 (1483, 'Facebook', 'Naver'),
 (1485, 'Naver', 'Facebook'),
 (1487, 'Naver', 'Instagram'),
 (1489, 'Organic', 'Organic'),
 (1491, 'Organic', 'Facebook'),
 (1493, 'Youtube', 'Youtube'),
 (1495, 'Facebook', 'Instagram'),
 (1497, 'Facebook', 'Youtube'),
 (1501, 'Google', 'Youtube'),
 (1503, 'Google', 'Facebook'),
 (1507, 'Facebook', 'Youtube'),
 (1511, 'Youtube', 'Instagram'),
 (1513, 'Facebook', 'Instagram'),
 (1515, 'Instagram', 'Instagram'),
 (1517, 'Instagram', 'Organic'),
 (1519, 'Organic', 'Youtube'),
 (1521, 'Organic', 'Youtube'),
 (1523, 'Facebook', 'Naver'),
 (1525, 'Naver', 'Youtube'),
 (1529, 'Youtube', 'Organic'),
 (1531, 'Facebook', 'Naver'),
 (1533, 'Instagram', 'Instagram'),
 (1535, 'Organic', 'Google'),
 (1537, 'Facebook', 'Organic'),
 (1539, 'Instagram', 'Google'),
 (1541, 'Google', 'Naver'),
 (1543, 'Instagram', 'Facebook'),
 (1545, 'Organic', 'Facebook'),
 (1547, 'Naver', 'Naver'),
 (1551, 'Facebook', 'Instagram'),
 (1555, 'Google', 'Google'),
 (1557, 'Naver', 'Organic'),
 (1559, 'Organic', 'Facebook'),
 (1563, 'Google', 'Organic'),
 (1565, 'Facebook', 'Instagram'),
 (1567, 'Instagram', 'Facebook'),
 (1569, 'Google', 'Youtube'),
 (1571, 'Facebook', 'Youtube'),
 (1573, 'Google', 'Google'),
 (1575, 'Organic', 'Naver'),
 (1577, 'Instagram', 'Youtube'),
 (1583, 'Naver', 'Youtube'),
 (1587, 'Instagram', 'Naver'),
 (1589, 'Facebook', 'Google'),
 (1591, 'Facebook', 'Youtube'),
 (1595, 'Instagram', 'Naver'),
 (1597, 'Instagram', 'Naver'),
 (1599, 'Facebook', 'Organic'),
 (1601, 'Youtube', 'Instagram'),
 (1603, 'Google', 'Instagram'),
 (1605, 'Facebook', 'Instagram'),
 (1607, 'Youtube', 'Organic'),
 (1609, 'Instagram', 'Instagram'),
 (1611, 'Google', 'Facebook'),
 (1613, 'Facebook', 'Facebook'),
 (1615, 'Organic', 'Google'),
 (1617, 'Facebook', 'Facebook'),
 (1619, 'Instagram', 'Organic'),
 (1621, 'Youtube', 'Facebook'),
 (1625, 'Naver', 'Youtube'),
 (1627, 'Google', 'Instagram'),
 (1631, 'Instagram', 'Organic'),
 (1635, 'Naver', 'Google'),
 (1637, 'Facebook', 'Facebook'),
 (1639, 'Facebook', 'Organic'),
 (1641, 'Google', 'Instagram'),
 (1643, 'Naver', 'Youtube'),
 (1645, 'Instagram', 'Facebook'),
 (1647, 'Youtube', 'Instagram'),
 (1649, 'Instagram', 'Facebook'),
 (1651, 'Google', 'Youtube'),
 (1653, 'Facebook', 'Youtube'),
 (1655, 'Facebook', 'Google'),
 (1657, 'Google', 'Facebook'),
 (1659, 'Google', 'Facebook'),
 (1661, 'Naver', 'Facebook'),
 (1663, 'Facebook', 'Naver'),
 (1665, 'Organic', 'Organic'),
 (1667, 'Youtube', 'Google'),
 (1671, 'Youtube', 'Youtube'),
 (1673, 'Instagram', 'Google'),
 (1675, 'Instagram', 'Naver'),
 (1677, 'Naver', 'Instagram'),
 (1679, 'Organic', 'Google'),
 (1681, 'Naver', 'Organic'),
 (1685, 'Instagram', 'Youtube'),
 (1687, 'Organic', 'Google'),
 (1689, 'Facebook', 'Facebook'),
 (1693, 'Instagram', 'Instagram'),
 (1695, 'Naver', 'Youtube'),
 (1697, 'Naver', 'Naver'),
 (1699, 'Naver', 'Facebook'),
 (1701, 'Instagram', 'Google'),
 (1703, 'Naver', 'Instagram'),
 (1705, 'Google', 'Instagram'),
 (1707, 'Facebook', 'Google'),
 (1709, 'Instagram', 'Facebook'),
 (1711, 'Naver', 'Facebook'),
 (1713, 'Google', 'Youtube'),
 (1717, 'Naver', 'Google'),
 (1719, 'Facebook', 'Youtube'),
 (1721, 'Google', 'Youtube'),
 (1723, 'Naver', 'Google'),
 (1725, 'Google', 'Organic'),
 (1727, 'Organic', 'Facebook'),
 (1729, 'Facebook', 'Google'),
 (1731, 'Google', 'Google'),
 (1733, 'Youtube', 'Facebook'),
 (1735, 'Facebook', 'Google'),
 (1737, 'Facebook', 'Google'),
 (1741, 'Organic', 'Google'),
 (1743, 'Facebook', 'Youtube'),
 (1745, 'Youtube', 'Organic'),
 (1749, 'Naver', 'Instagram'),
 (1753, 'Naver', 'Organic'),
 (1755, 'Google', 'Organic'),
 (1757, 'Naver', 'Instagram'),
 (1759, 'Instagram', 'Google'),
 (1761, 'Naver', 'Naver'),
 (1767, 'Instagram', 'Instagram'),
 (1769, 'Youtube', 'Google'),
 (1771, 'Youtube', 'Naver'),
 (1772, 'Instagram', 'Instagram'),
 (1773, 'Google', 'Google'),
 (1775, 'Instagram', 'Naver'),
 (1777, 'Google', 'Organic'),
 (1779, 'Google', 'Naver'),
 (1783, 'Youtube', 'Facebook'),
 (1785, 'Organic', 'Youtube'),
 (1787, 'Youtube', 'Organic'),
 (1789, 'Facebook', 'Organic'),
 (1791, 'Naver', 'Youtube'),
 (1793, 'Naver', 'Youtube'),
 (1795, 'Google', 'Google'),
 (1797, 'Organic', 'Naver'),
 (1799, 'Facebook', 'Organic'),
 (1801, 'Google', 'Youtube'),
 (1803, 'Instagram', 'Naver'),
 (1805, 'Facebook', 'Naver'),
 (1807, 'Naver', 'Facebook'),
 (1809, 'Youtube', 'Google'),
 (1811, 'Organic', 'Organic'),
 (1815, 'Facebook', 'Instagram'),
 (1817, 'Organic', 'Naver'),
 (1819, 'Google', 'Youtube'),
 (1821, 'Naver', 'Instagram'),
 (1823, 'Google', 'Facebook'),
 (1825, 'Naver', 'Google'),
 (1827, 'Youtube', 'Naver'),
 (1829, 'Naver', 'Organic'),
 (1831, 'Youtube', 'Naver'),
 (1835, 'Organic', 'Google'),
 (1837, 'Naver', 'Instagram'),
 (1839, 'Instagram', 'Facebook'),
 (1849, 'Google', 'Instagram'),
 (1851, 'Facebook', 'Naver'),
 (1853, 'Organic', 'Instagram'),
 (1855, 'Organic', 'Google'),
 (1857, 'Google', 'Organic'),
 (1861, 'Organic', 'Naver'),
 (1871, 'Facebook', 'Youtube'),
 (1873, 'Naver', 'Google'),
 (1875, 'Youtube', 'Naver'),
 (1877, 'Naver', 'Facebook'),
 (1879, 'Youtube', 'Naver'),
 (1881, 'Organic', 'Organic'),
 (1883, 'Organic', 'Youtube'),
 (1885, 'Instagram', 'Youtube'),
 (1887, 'Organic', 'Youtube'),
 (1889, 'Instagram', 'Naver'),
 (1891, 'Naver', 'Facebook'),
 (1893, 'Youtube', 'Naver'),
 (1895, 'Facebook', 'Youtube'),
 (1897, 'Facebook', 'Naver'),
 (1899, 'Youtube', 'Organic'),
 (1901, 'Instagram', 'Naver'),
 (1903, 'Facebook', 'Instagram'),
 (1907, 'Facebook', 'Facebook'),
 (1909, 'Google', 'Facebook'),
 (1911, 'Facebook', 'Facebook'),
 (1915, 'Naver', 'Google'),
 (1917, 'Instagram', 'Instagram'),
 (1919, 'Organic', 'Naver'),
 (1921, 'Instagram', 'Google'),
 (1927, 'Google', 'Organic'),
 (1929, 'Organic', 'Organic'),
 (1931, 'Google', 'Google'),
 (1935, 'Facebook', 'Naver'),
 (1937, 'Google', 'Google'),
 (1941, 'Facebook', 'Organic'),
 (1943, 'Organic', 'Facebook'),
 (1945, 'Facebook', 'Organic'),
 (1947, 'Organic', 'Instagram'),
 (1949, 'Youtube', 'Organic'),
 (1951, 'Facebook', 'Organic'),
 (1953, 'Google', 'Facebook'),
 (1955, 'Instagram', 'Organic'),
 (1957, 'Instagram', 'Organic'),
 (1959, 'Google', 'Youtube'),
 (1961, 'Organic', 'Youtube'),
 (1963, 'Google', 'Organic'),
 (1965, 'Facebook', 'Youtube'),
 (1967, 'Youtube', 'Naver'),
 (1971, 'Instagram', 'Youtube'),
 (1973, 'Organic', 'Organic'),
 (1975, 'Google', 'Instagram'),
 (1977, 'Organic', 'Organic'),
 (1979, 'Instagram', 'Instagram'),
 (1981, 'Facebook', 'Naver'),
 (1983, 'Youtube', 'Organic'),
 (1985, 'Facebook', 'Facebook'),
 (1987, 'Organic', 'Facebook'),
 (1989, 'Youtube', 'Instagram'),
 (1991, 'Google', 'Organic'),
 (1993, 'Naver', 'Google'),
 (1995, 'Facebook', 'Instagram'),
 (1997, 'Youtube', 'Youtube'),
 (1999, 'Google', 'Youtube'),
 (2001, 'Youtube', 'Instagram'),
 (2005, 'Google', 'Organic'),
 (2007, 'Youtube', 'Naver'),
 (2009, 'Youtube', 'Facebook'),
 (2011, 'Instagram', 'Organic'),
 (2013, 'Instagram', 'Youtube'),
 (2017, 'Instagram', 'Naver'),
 (2019, 'Facebook', 'Youtube'),
 (2021, 'Youtube', 'Google'),
 (2025, 'Instagram', 'Naver'),
 (2027, 'Youtube', 'Facebook'),
 (2029, 'Youtube', 'Naver'),
 (2035, 'Instagram', 'Instagram'),
 (2037, 'Youtube', 'Google'),
 (2039, 'Facebook', 'Youtube'),
 (2041, 'Organic', 'Instagram'),
 (2043, 'Facebook', 'Facebook'),

Assignment 3
* Gross Revenue가 가장 큰 UserID 10개 찾기
  * Gross revenue: Refund 포함한 매출. Refund등의 비용이 빠지면 Net revenue
  * 반드시 SQL로 해보기

In [88]:
%%sql

SELECT userid,sum(amount) AS Gross_revenue,
        SUM(CASE WHEN refunded is False then amount end ) AS Net_revenue 
FROM raw_data.session_transaction st
JOIN raw_data.user_session_channel usc ON st.sessionid = usc.sessionid
group by userid
order by gross_revenue desc
limit 10;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
10 rows affected.

[(989, 743, 743),
 (772, 556, 556),
 (1615, 506, 506),
 (654, 488, 488),
 (1651, 463, 463),
 (973, 438, 438),
 (262, 422, 422),
 (1099, 421, 343),
 (2682, 414, 414),
 (891, 412, 412)]

Assignment 4

채널별 월 매출액 테이블 만들기 (본인 스키마 밑에 CTAS로 테이블 만들기)

1. session_timestamp, user_session_channel, session_transaction
테이블들을 사용
2. 아래와 같은 필드로 구성
* year-month
* channel
* uniqueUsers (총방문 사용자)
* paidUsers (구매 사용자: refund한 경우도 판매로 고려) -> CASE WHEN 사용
* conversionRate (구매사용자 / 총방문 사용자)
* Casting이 필요. 분모는 NULLIF로 0으로 나누기 방지 grossRevenue (refund 포함)
* netRevenue (refund 제외) -> CASE WHEN 사용

In [89]:
%%sql

select left(ts,7) as "month", usc.channel,Count(Distinct userid) AS uniqueUsers
FROM raw_data.user_session_channel as usc
left join raw_data.session_timestamp as t ON t.sessionid = usc.sessionid
left join raw_data.session_transaction as st ON st.sessionid = usc.sessionid
group by 1,2
order by 1,2;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
42 rows affected.

[('2019-05', 'Facebook', 247),
 ('2019-05', 'Google', 253),
 ('2019-05', 'Instagram', 234),
 ('2019-05', 'Naver', 237),
 ('2019-05', 'Organic', 238),
 ('2019-05', 'Youtube', 244),
 ('2019-06', 'Facebook', 414),
 ('2019-06', 'Google', 412),
 ('2019-06', 'Instagram', 410),
 ('2019-06', 'Naver', 398),
 ('2019-06', 'Organic', 416),
 ('2019-06', 'Youtube', 400),
 ('2019-07', 'Facebook', 558),
 ('2019-07', 'Google', 556),
 ('2019-07', 'Instagram', 567),
 ('2019-07', 'Naver', 553),
 ('2019-07', 'Organic', 557),
 ('2019-07', 'Youtube', 564),
 ('2019-08', 'Facebook', 611),
 ('2019-08', 'Google', 610),
 ('2019-08', 'Instagram', 621),
 ('2019-08', 'Naver', 626),
 ('2019-08', 'Organic', 608),
 ('2019-08', 'Youtube', 614),
 ('2019-09', 'Facebook', 597),
 ('2019-09', 'Google', 599),
 ('2019-09', 'Instagram', 588),
 ('2019-09', 'Naver', 592),
 ('2019-09', 'Organic', 592),
 ('2019-09', 'Youtube', 588),
 ('2019-10', 'Facebook', 698),
 ('2019-10', 'Google', 699),
 ('2019-10', 'Instagram', 707),
 ('2019-10', 'Naver', 713),
 ('2019-10', 'Organic', 709),
 ('2019-10', 'Youtube', 705),
 ('2019-11', 'Facebook', 688),
 ('2019-11', 'Google', 688),
 ('2019-11', 'Instagram', 669),
 ('2019-11', 'Naver', 667),
 ('2019-11', 'Organic', 677),
 ('2019-11', 'Youtube', 677)]

In [90]:
%%sql

SELECT LEFT(ts, 7) "month",
usc.channel,
COUNT(DISTINCT userid) uniqueUsers,
COUNT(DISTINCT (CASE WHEN amount >= 0 THEN userid END)) paidUsers, ROUND(paidUsers::decimal*100/NULLIF(uniqueUsers, 0),2) conversionRate, SUM(amount) grossRevenue,
SUM(CASE WHEN refunded is not True THEN amount END) netRevenue FROM raw_data.user_session_channel usc
LEFT JOIN raw_data.session_timestamp t ON t.sessionid = usc.sessionid LEFT JOIN raw_data.session_transaction st ON st.sessionid = usc.sessionid GROUP BY 1, 2
ORDER BY 1, 2;

 * postgresql://wmfrlek99:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
42 rows affected.

[('2019-05', 'Facebook', 247, 14, Decimal('5.67'), 1199, 997),
 ('2019-05', 'Google', 253, 10, Decimal('3.95'), 580, 580),
 ('2019-05', 'Instagram', 234, 11, Decimal('4.70'), 959, 770),
 ('2019-05', 'Naver', 237, 11, Decimal('4.64'), 867, 844),
 ('2019-05', 'Organic', 238, 17, Decimal('7.14'), 1846, 1571),
 ('2019-05', 'Youtube', 244, 10, Decimal('4.10'), 529, 529),
 ('2019-06', 'Facebook', 414, 22, Decimal('5.31'), 1578, 1578),
 ('2019-06', 'Google', 412, 13, Decimal('3.16'), 947, 947),
 ('2019-06', 'Instagram', 410, 21, Decimal('5.12'), 1462, 1418),
 ('2019-06', 'Naver', 398, 15, Decimal('3.77'), 1090, 1090),
 ('2019-06', 'Organic', 416, 14, Decimal('3.37'), 1129, 940),
 ('2019-06', 'Youtube', 400, 17, Decimal('4.25'), 1042, 1042),
 ('2019-07', 'Facebook', 558, 32, Decimal('5.73'), 2222, 2144),
 ('2019-07', 'Google', 556, 21, Decimal('3.78'), 1558, 1385),
 ('2019-07', 'Instagram', 567, 25, Decimal('4.41'), 1896, 1766),
 ('2019-07', 'Naver', 553, 19, Decimal('3.44'), 1547, 1547),
 ('2019-07', 'Organic', 557, 24, Decimal('4.31'), 1600, 1600),
 ('2019-07', 'Youtube', 564, 36, Decimal('6.38'), 2210, 2037),
 ('2019-08', 'Facebook', 611, 18, Decimal('2.95'), 1009, 1009),
 ('2019-08', 'Google', 610, 28, Decimal('4.59'), 2210, 1894),
 ('2019-08', 'Instagram', 621, 28, Decimal('4.51'), 2129, 2001),
 ('2019-08', 'Naver', 626, 22, Decimal('3.51'), 1829, 1551),
 ('2019-08', 'Organic', 608, 26, Decimal('4.28'), 1643, 1606),
 ('2019-08', 'Youtube', 614, 18, Decimal('2.93'), 987, 950),
 ('2019-09', 'Facebook', 597, 27, Decimal('4.52'), 2270, 2270),
 ('2019-09', 'Google', 599, 25, Decimal('4.17'), 1872, 1691),
 ('2019-09', 'Instagram', 588, 20, Decimal('3.40'), 1260, 1122),
 ('2019-09', 'Naver', 592, 21, Decimal('3.55'), 1996, 1996),
 ('2019-09', 'Organic', 592, 23, Decimal('3.89'), 1267, 1267),
 ('2019-09', 'Youtube', 588, 15, Decimal('2.55'), 1301, 1301),
 ('2019-10', 'Facebook', 698, 29, Decimal('4.15'), 1650, 1641),
 ('2019-10', 'Google', 699, 30, Decimal('4.29'), 2150, 2098),
 ('2019-10', 'Instagram', 707, 34, Decimal('4.81'), 2568, 2395),
 ('2019-10', 'Naver', 713, 32, Decimal('4.49'), 2695, 2695),
 ('2019-10', 'Organic', 709, 31, Decimal('4.37'), 2762, 2608),
 ('2019-10', 'Youtube', 705, 34, Decimal('4.82'), 2492, 2319),
 ('2019-11', 'Facebook', 688, 26, Decimal('3.78'), 1678, 1678),
 ('2019-11', 'Google', 688, 26, Decimal('3.78'), 2286, 2235),
 ('2019-11', 'Instagram', 669, 25, Decimal('3.74'), 2116, 2116),
 ('2019-11', 'Naver', 667, 26, Decimal('3.90'), 2234, 1987),
 ('2019-11', 'Organic', 677, 34, Decimal('5.02'), 2626, 2255),
 ('2019-11', 'Youtube', 677, 46, Decimal('6.79'), 3532, 3331)]